eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    hostname: localhost

microservice:
  security:
    endpoints:
      endpoint:
        uri: http://SECURITY/api/security/test
